### ISSUE TITLE
Im having difficulties installing pesapal in laravel 4.2.* 

### ISSUE THREAD

**Issue by younggeeks** [ericmuigai/pesapal#1]
![untitled](https://cloud.githubusercontent.com/assets/5984570/4259846/a0bc54bc-3b16-11e4-9322-b6dc712a817a.png)

**Comment by ericmuigai** [comment]
Hello @younggeeks I have updated it to the latest Laravel version..

**Comment by ratatatKE** [comment]
Hi Eric
Please update the documentation as well Eric, so that we can easily integrate it to L5. Apparently L5 handles service providers differently. I think your package works with L5, however, am having hell getting it up and running.
#entitlement

**Comment by ericmuigai** [comment]
Hi ratatKe,
I will look at it and hopefully update it.
