### ISSUE TITLE
Package not found in any version

### ISSUE THREAD

**Issue by GaurangGhinaiya** [ericmuigai/pesapal#2]
![image](https://cloud.githubusercontent.com/assets/10466849/11760802/98e0e742-a0cf-11e5-9e07-d0d6ceaaf34f.png)

**Comment by ericmuigai** [comment]
Hello, I am looking to upgrade it. This will fix the problem.
I will update you asap

**Comment by GaurangGhinaiya** [comment]
OK
Thanks

**Comment by ericmuigai** [comment]
Hello @GaurangGhinaiya  I have updated and fixed those issues.
Thanks
